spring.application.name=authentication_service
app.jwt.secret=${JWTSECRET}
app.jwt.expiration-ms=86400000
spring.threads.virtual.enabled=true


#Database Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://${BILLINGSDBHOST}:${BILLINGSDBPORT}/billings
spring.datasource.username=${BILLINGSDBUSER}
spring.datasource.password=${BILLINGSDBPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

#swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs